name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install flask coverage
      - name: Run unit tests with coverage
        run: coverage run -m unittest tests/appTest.py
      - name: Display coverage report
        run: coverage report

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Display test message
        run: echo "Additional test stage - test-job2 completed successfully!"

  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        run: echo "Olá, ${{ github.actor }}!"

  deploy-prod-job:
    runs-on: ubuntu-latest
    environment:
      name: Deploy com permissao
      url: https://example.com
    steps:
      - name: Deploy to production
        run: |
          echo "Implantando a branch ${{ github.ref_name }} em produção..."
          sleep 20
          echo "Implantação concluída com sucesso!"

  semgrep-sast:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep SAST
        run: |
          pip install semgrep
          semgrep --json --config=p/security-audit > gl-sast-report.json || true
      - name: Upload SAST Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sast-report
          path: gl-sast-report.json

  check-sast-report:
    runs-on: ubuntu-latest
    container: python:latest
    needs: semgrep-sast
    steps:
      - uses: actions/checkout@v3
      - name: Download SAST Report
        uses: actions/download-artifact@v3
        with:
          name: sast-report
      - name: Validate SAST Report
        run: python3 validate_sast.py
