name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install flask coverage
      - name: Run unit tests with coverage
        run: coverage run -m unittest tests/appTest.py
      - name: Display coverage report
        run: coverage report

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Display test message
        run: echo "Additional test stage - test-job2 completed successfully!"

  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        run: echo "Olá, ${{ github.actor }}!"

  deploy-prod-job:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
      - name: Deploy to production
        run: |
          echo "Implantando a branch ${{ github.ref_name }} em produção..."
          sleep 20
          echo "Implantação concluída com sucesso!"
